-- create "users" table
CREATE TABLE "users"
(
    "id"         bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" character varying NOT NULL,
    "last_name"  character varying NOT NULL,
    birthday     timestamp         NOT NULL,
    "updated_at" timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- create task status
create type task_status as enum (
    'todo',
    'in_progress',
    'done'
    );

-- create "tasks" table
CREATE TABLE "tasks"
(
    "id"             bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title"          character varying NOT NULL,
    "note"           text              NOT NULL,
    "status"         task_status       NOT NULL,
    "updated_at"     timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at"     timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id"        bigint            NULL,
    "parent_task_id" bigint            NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "tasks_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL,
    CONSTRAINT "tasks_tasks" FOREIGN KEY ("parent_task_id") REFERENCES "tasks" ("id") ON DELETE SET NULL
);

-- create project status
create type project_status as enum (
    'todo',
    'in_progress',
    'done'
    );

-- create "projects" table
CREATE TABLE "projects"
(
    "id"          bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title"       character varying NOT NULL,
    "description" text              NOT NULL,
    "status"      project_status    NOT NULL,
    "updated_at"  timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at"  timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- create "project_tasks" table
CREATE TABLE "project_tasks"
(
    "project_id" bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "task_id"    bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("project_id", "task_id"),
    CONSTRAINT "project_task_projects" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE SET NULL,
    CONSTRAINT "project_task_tasks" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE SET NULL
);
