-- create "users" table
CREATE TABLE "users"
(
    "id"         bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" character varying NOT NULL,
    "last_name"  character varying NOT NULL,
    "birthday"   date              NULL,
    "updated_at" timestamptz       NOT NULL,
    "created_at" timestamptz       NOT NULL,
    PRIMARY KEY ("id")
);
-- create "tasks" table
CREATE TABLE "tasks"
(
    "id"            bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title"         character varying NOT NULL,
    "note"          character varying NOT NULL,
    "status"        character varying NOT NULL,
    "updated_at"    timestamptz       NOT NULL,
    "created_at"    timestamptz       NOT NULL,
    "task_children" bigint            NULL,
    "user_tasks"    bigint            NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "tasks_tasks_children" FOREIGN KEY ("task_children") REFERENCES "tasks" ("id") ON DELETE SET NULL,
    CONSTRAINT "tasks_users_tasks" FOREIGN KEY ("user_tasks") REFERENCES "users" ("id") ON DELETE SET NULL
);
-- create "projects" table
CREATE TABLE "projects"
(
    "id"          bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title"       character varying NOT NULL,
    "description" character varying NOT NULL,
    "status"      character varying NOT NULL,
    "updated_at"  timestamptz       NOT NULL,
    "created_at"  timestamptz       NOT NULL,
    PRIMARY KEY ("id")
);
-- create "project_tasks" table
CREATE TABLE "project_tasks"
(
    "project_id" bigint NOT NULL,
    "task_id"    bigint NOT NULL,
    PRIMARY KEY ("project_id", "task_id"),
    CONSTRAINT "project_tasks_project_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE,
    CONSTRAINT "project_tasks_task_id" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE CASCADE
);
