// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ProjectTasks     string
	Projects         string
	SchemaMigrations string
	Tasks            string
	Users            string
}{
	ProjectTasks:     "project_tasks",
	Projects:         "projects",
	SchemaMigrations: "schema_migrations",
	Tasks:            "tasks",
	Users:            "users",
}
