-- create "users" table
CREATE TABLE "users"
(
    "id"         bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" character varying NOT NULL,
    "last_name"  character varying NOT NULL,
    "updated_at" timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- create todos status
create type status as enum (
    'todo',
    'in_progress',
    'done'
    );

-- create "todos" table
CREATE TABLE "todos"
(
    "id"          bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title"       character varying NOT NULL,
    "description" text              NOT NULL,
    "status"      status            NOT NULL,
    "updated_at"  timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at"  timestamptz       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id"     bigint            NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "todos_users_todos" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL
);
