version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - go-orm-pg-data:/var/lib/go-orm-postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"

volumes:
  go-orm-pg-data: