// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserWithTodo(ctx context.Context, id int64) ([]GetUserWithTodoRow, error)
}

var _ Querier = (*Queries)(nil)
